server.port=8080

#db
spring.datasource.url=jdbc:oracle:thin:@tufdb_tp?TNS_ADMIN=${secrets.WALLET_PATH}
spring.datasource.username=${secrets.DB_USER}
spring.datasource.password=${secrets.DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jwt.secret=${secrets.JWT_SECRET}

logging.level.root=warn

#jpa
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=false

#ollama
spring.ai.ollama.base-url=${secrets.OLLAMA_BASE_URL}
spring.ai.ollama.chat.options.model=${secrets.OLLAMA_MODEL}

#kure embedding api
kure.embedding.url=${secrets.KURE_EMBEDDING_URL}

tuf-front.url=${secrets.TUF_FRONT_URL}