spring.application.name=tuf
app.git-commit=${gitCommit}
app.git-branch=${gitBranch}
app.build-time=${buildTime}

spring.profiles.active=local

#mybatis
mybatis.mapper-locations=classpath:mybatis/mappers/*.xml
mybatis.type-aliases-package=io.github.gyulbbe
mybatis.type-handlers-package=io.github.gyulbbe.common.utils.embeddingVector

#null
mybatis.configuration.jdbc-type-for-null=NULL

#jpa
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=100

#swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html