spring.application.name=tuf
app.git-commit=${gitCommit}
app.git-branch=${gitBranch}
app.build-time=${buildTime}
server.port=80
#db
spring.datasource.url=jdbc:oracle:thin:@localhost:1522/FREEPDB1?characterEncoding=AL32UTF8
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.username=tuf
spring.datasource.password=1234

spring.jwt.secret=tuf-back

logging.level.root=info

#mybatis
mybatis.mapper-locations=classpath:mybatis/mappers/*.xml
mybatis.type-aliases-package=io.github.gyulbbe
mybatis.type-handlers-package=io.github.gyulbbe.common.utils.embeddingVector

#null
mybatis.configuration.jdbc-type-for-null=NULL

#jpa
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=100

#ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=gemma4:e4b

#kure embedding api
kure.embedding.url=http://localhost:8000

tuf-front.url=http://localhost:5173

#swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html