package io.github.gyulbbe.draft.dto;

public enum DraftLiveEventType {
    SESSION_STARTED,
    SESSION_PAUSED,
    SESSION_RESUMED,
    DRAG_PREVIEW,
    PICK_COMPLETED,
    TURN_CHANGED,
    TIMER_EXTENDED,
    PICK_SKIPPED,
    AI_PICK_REVIEW_READY,
    AI_RECOMMENDATION_READY,
    SESSION_FINISHED,
    SNAPSHOT_SYNC_REQUIRED
}
