/* ==============================================
   1. 기본 정보 테이블
   ============================================== */

CREATE SEQUENCE users_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE users (
    id NUMBER DEFAULT users_seq.NEXTVAL PRIMARY KEY,
    user_id VARCHAR2(255) NOT NULL,
    password VARCHAR2(255) NOT NULL,
    name VARCHAR2(50),
    phone VARCHAR2(50),
    tier VARCHAR2(50),
    race VARCHAR2(10) CHECK (race IN ('ZERG', 'TERRAN', 'PROTOSS', 'RANDOM')),
    user_type VARCHAR2(20) CHECK (user_type IN ('ROLE_USER', 'ROLE_MANAGER', 'ROLE_MASTER', 'ROLE_ADMIN')),
    battle_tag VARCHAR2(50),
    status VARCHAR2(10) CHECK (status IN ('ACTIVE', 'BANNED', 'INACTIVE')),
    coin NUMBER,
    photo VARCHAR2(255),
    reg_date DATE DEFAULT SYSDATE,
    update_date DATE DEFAULT SYSDATE
);

CREATE TABLE site_menu_visibility (
    menu_key VARCHAR2(100 CHAR) PRIMARY KEY,
    visible NUMBER(1) DEFAULT 1 NOT NULL,
    updated_by NUMBER,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT chk_site_menu_visibility_visible CHECK (visible IN (0, 1)),
    CONSTRAINT fk_site_menu_visibility_updated_by FOREIGN KEY (updated_by) REFERENCES users(id)
);

CREATE TABLE ai_chat_settings (
    setting_key VARCHAR2(50 CHAR) PRIMARY KEY,
    routing_mode VARCHAR2(30 CHAR) DEFAULT 'AUTO' NOT NULL,
    cloudflare_model VARCHAR2(255 CHAR) NOT NULL,
    ollama_model VARCHAR2(255 CHAR) NOT NULL,
    updated_by NUMBER,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT chk_ai_chat_settings_key CHECK (setting_key = 'default'),
    CONSTRAINT chk_ai_chat_settings_mode
        CHECK (routing_mode IN ('AUTO', 'CLOUDFLARE_ONLY', 'OLLAMA_ONLY')),
    CONSTRAINT fk_ai_chat_settings_updated_by FOREIGN KEY (updated_by) REFERENCES users(id)
);

CREATE TABLE home_schedules (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_group VARCHAR2(50) NOT NULL,
    title VARCHAR2(200) NOT NULL,
    description VARCHAR2(1000),
    scheduled_at TIMESTAMP NOT NULL,
    target_url VARCHAR2(500),
    link_type VARCHAR2(20) DEFAULT 'DIRECT' NOT NULL,
    display_priority NUMBER DEFAULT 0 NOT NULL,
    reg_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    update_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT chk_home_schedules_link_type
        CHECK (link_type IN ('DIRECT', 'REDIRECT'))
);

CREATE SEQUENCE leagues_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE leagues (
    id NUMBER DEFAULT leagues_seq.NEXTVAL PRIMARY KEY,
    league_name VARCHAR2(50) NOT NULL,
    season_name VARCHAR2(100),
    description VARCHAR2(1000),
    status VARCHAR2(20) DEFAULT 'READY' NOT NULL,
    league_type VARCHAR2(50) NOT NULL,
    start_date DATE,
    end_date DATE,
    draft_session_id NUMBER,
    tournament_id NUMBER,
    champion_team_id NUMBER,
    runner_up_team_id NUMBER,
    reg_date DATE DEFAULT SYSDATE,
    update_date DATE DEFAULT SYSDATE,
    CONSTRAINT chk_leagues_status
        CHECK (status IN ('READY', 'LIVE', 'FINISHED'))
);

CREATE SEQUENCE maps_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE maps (
    id NUMBER DEFAULT maps_seq.NEXTVAL PRIMARY KEY,
    map_name VARCHAR2(255),
    image VARCHAR2(255),
    reg_date DATE DEFAULT SYSDATE,
    update_date DATE DEFAULT SYSDATE,
    CONSTRAINT uk_maps_map_name UNIQUE (map_name)
);

CREATE SEQUENCE home_schedule_matches_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE home_schedule_matches (
    id NUMBER DEFAULT home_schedule_matches_seq.NEXTVAL PRIMARY KEY,
    schedule_id NUMBER NOT NULL,
    display_order NUMBER(4) NOT NULL,
    set_label VARCHAR2(50 CHAR) NOT NULL,
    match_format VARCHAR2(20 CHAR) DEFAULT '1V1' NOT NULL,
    team_a_name VARCHAR2(100 CHAR),
    team_b_name VARCHAR2(100 CHAR),
    map_id NUMBER,
    note VARCHAR2(300 CHAR),
    reg_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    update_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_home_schedule_matches_schedule
        FOREIGN KEY (schedule_id) REFERENCES home_schedules(id) ON DELETE CASCADE,
    CONSTRAINT fk_home_schedule_matches_map
        FOREIGN KEY (map_id) REFERENCES maps(id),
    CONSTRAINT chk_home_schedule_matches_order
        CHECK (display_order > 0),
    CONSTRAINT chk_home_schedule_matches_format
        CHECK (match_format IN ('1V1', '2V2', '3V3', 'ACE', 'CUSTOM'))
);

CREATE SEQUENCE home_schedule_match_players_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE home_schedule_match_players (
    id NUMBER DEFAULT home_schedule_match_players_seq.NEXTVAL PRIMARY KEY,
    match_id NUMBER NOT NULL,
    side VARCHAR2(1 CHAR) NOT NULL,
    slot_order NUMBER(2) NOT NULL,
    user_id NUMBER,
    player_name VARCHAR2(100 CHAR),
    player_rank VARCHAR2(20 CHAR),
    player_race VARCHAR2(20 CHAR),
    note VARCHAR2(300 CHAR),
    reg_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    update_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_home_schedule_match_players_match
        FOREIGN KEY (match_id) REFERENCES home_schedule_matches(id) ON DELETE CASCADE,
    CONSTRAINT fk_home_schedule_match_players_user
        FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uq_home_schedule_match_players_slot
        UNIQUE (match_id, side, slot_order),
    CONSTRAINT chk_home_schedule_match_players_side
        CHECK (side IN ('A', 'B')),
    CONSTRAINT chk_home_schedule_match_players_order
        CHECK (slot_order > 0),
    CONSTRAINT chk_home_schedule_match_players_name
        CHECK (user_id IS NOT NULL OR player_name IS NOT NULL),
    CONSTRAINT chk_home_schedule_match_players_race
        CHECK (player_race IS NULL OR player_race IN ('ZERG', 'TERRAN', 'PROTOSS', 'RANDOM'))
);

/* ==============================================
   2. 리그 및 팀 테이블
   ============================================== */

CREATE SEQUENCE proleague_teams_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE proleague_teams (
    id NUMBER DEFAULT proleague_teams_seq.NEXTVAL PRIMARY KEY,
    team_name VARCHAR2(255),
    league_id NUMBER,
    team_leader_id NUMBER,
    vice_leader_id NUMBER,
    display_order NUMBER DEFAULT 1 NOT NULL,
    draft_team_id NUMBER,
    reg_date DATE DEFAULT SYSDATE,
    update_date DATE DEFAULT SYSDATE,
    CONSTRAINT fk_proleague_team_league FOREIGN KEY (league_id) REFERENCES leagues(id),
    CONSTRAINT fk_proleague_team_leader FOREIGN KEY (team_leader_id) REFERENCES users(id),
    CONSTRAINT fk_proleague_team_vice_leader FOREIGN KEY (vice_leader_id) REFERENCES users(id)
);

CREATE SEQUENCE proleague_team_members_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE proleague_team_members (
    id NUMBER DEFAULT proleague_team_members_seq.NEXTVAL PRIMARY KEY,
    league_id NUMBER NOT NULL,
    proleague_team_id NUMBER NOT NULL,
    user_id NUMBER NOT NULL,
    source VARCHAR2(20 CHAR) DEFAULT 'DRAFT' NOT NULL,
    source_draft_session_id NUMBER,
    draft_pick_no NUMBER(6),
    display_order NUMBER(6) DEFAULT 1 NOT NULL,
    status VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    reg_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    update_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_proleague_team_member_league
        FOREIGN KEY (league_id) REFERENCES leagues(id),
    CONSTRAINT fk_proleague_team_member_team
        FOREIGN KEY (proleague_team_id) REFERENCES proleague_teams(id),
    CONSTRAINT fk_proleague_team_member_user
        FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uq_proleague_team_member_league_user_status
        UNIQUE (league_id, user_id, status),
    CONSTRAINT chk_proleague_team_member_source
        CHECK (source IN ('DRAFT', 'MANUAL')),
    CONSTRAINT chk_proleague_team_member_status
        CHECK (status IN ('ACTIVE', 'REMOVED')),
    CONSTRAINT chk_proleague_team_member_display_order
        CHECK (display_order > 0)
);

CREATE SEQUENCE league_participations_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE league_participations (
    id NUMBER DEFAULT league_participations_seq.NEXTVAL PRIMARY KEY,
    league_id NUMBER,
    user_id NUMBER,
    race VARCHAR2(10) CHECK (race IN ('ZERG', 'TERRAN', 'PROTOSS', 'RANDOM')),
    status VARCHAR2(10) CHECK (status IN ('ACTIVE', 'BANNED')),
    reg_date DATE DEFAULT SYSDATE,
    update_date DATE DEFAULT SYSDATE,
    CONSTRAINT fk_league_participation_league FOREIGN KEY (league_id) REFERENCES leagues(id),
    CONSTRAINT fk_league_participation_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE SEQUENCE series_infos_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE series_infos (
    id NUMBER DEFAULT series_infos_seq.NEXTVAL PRIMARY KEY,
    league_id NUMBER,
    round VARCHAR2(50),
    title VARCHAR2(255),
    match_date DATE,
    reg_date DATE DEFAULT SYSDATE,
    update_date DATE DEFAULT SYSDATE,
    CONSTRAINT fk_series_info_league FOREIGN KEY (league_id) REFERENCES leagues(id)
);

/* ==============================================
   3. 경기 관련 테이블
   ============================================== */

CREATE SEQUENCE match_infos_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE match_infos (
    id NUMBER DEFAULT match_infos_seq.NEXTVAL PRIMARY KEY,
    league_id NUMBER,
    series_info_id NUMBER,
    map_id NUMBER,
    match_type VARCHAR2(50),
    format VARCHAR2(50),
    set_number NUMBER,
    reg_date DATE DEFAULT SYSDATE,
    update_date DATE DEFAULT SYSDATE,
    CONSTRAINT fk_match_info_league FOREIGN KEY (league_id) REFERENCES leagues(id),
    CONSTRAINT fk_match_info_series_info FOREIGN KEY (series_info_id) REFERENCES series_infos(id),
    CONSTRAINT fk_match_info_map FOREIGN KEY (map_id) REFERENCES maps(id)
);

CREATE SEQUENCE match_players_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE match_players (
    id NUMBER DEFAULT match_players_seq.NEXTVAL PRIMARY KEY,
    user_id NUMBER,
    player_id VARCHAR2(255),
    player_name VARCHAR2(50),
    match_info_id NUMBER,
    proleague_team_id NUMBER,
    race VARCHAR2(10) CHECK (race IN ('ZERG', 'TERRAN', 'PROTOSS', 'RANDOM')),
    result VARCHAR2(10) CHECK (result IN ('WIN', 'LOSE', 'DRAW')),
    remark VARCHAR2(4000),
    reg_date DATE DEFAULT SYSDATE,
    update_date DATE DEFAULT SYSDATE,
    CONSTRAINT fk_match_player_match_info FOREIGN KEY (match_info_id) REFERENCES match_infos(id),
    CONSTRAINT fk_match_player_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_match_player_team FOREIGN KEY (proleague_team_id) REFERENCES proleague_teams(id)
);

CREATE SEQUENCE commentaries_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE commentaries (
    id NUMBER DEFAULT commentaries_seq.NEXTVAL PRIMARY KEY,
    user_id NUMBER,
    match_info_id NUMBER,
    type VARCHAR2(50),
    match_summary VARCHAR2(4000),
    reg_date DATE DEFAULT SYSDATE,
    update_date DATE DEFAULT SYSDATE,
    CONSTRAINT fk_commentary_match_info FOREIGN KEY (match_info_id) REFERENCES match_infos(id),
    CONSTRAINT fk_commentary_user FOREIGN KEY (user_id) REFERENCES users(id)
);

/* ==============================================
   4. 커뮤니티 및 로그 테이블
   ============================================== */

CREATE SEQUENCE boards_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE boards (
    id NUMBER DEFAULT boards_seq.NEXTVAL PRIMARY KEY,
    user_id NUMBER,
    author_name VARCHAR2(50) NOT NULL,
    title VARCHAR2(255),
    text CLOB,
    reg_date DATE DEFAULT SYSDATE,
    update_date DATE DEFAULT SYSDATE,
    CONSTRAINT fk_board_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE SEQUENCE comments_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE comments (
    id NUMBER DEFAULT comments_seq.NEXTVAL PRIMARY KEY,
    board_id NUMBER NOT NULL,
    user_id NUMBER,
    author_name VARCHAR2(50) NOT NULL,
    parent_id NUMBER,
    depth NUMBER DEFAULT 0 NOT NULL,
    content VARCHAR2(4000) NOT NULL,
    reg_date DATE DEFAULT SYSDATE,
    update_date DATE DEFAULT SYSDATE,
    CONSTRAINT chk_comments_depth CHECK (depth >= 0),
    CONSTRAINT fk_comment_board FOREIGN KEY (board_id) REFERENCES boards(id) ON DELETE CASCADE,
    CONSTRAINT fk_comment_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_comment_parent FOREIGN KEY (parent_id) REFERENCES comments(id) ON DELETE CASCADE
);

CREATE SEQUENCE traces_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE traces (
    id NUMBER DEFAULT traces_seq.NEXTVAL PRIMARY KEY,
    user_id NUMBER,
    type VARCHAR2(255),
    text VARCHAR2(4000),
    reg_date DATE DEFAULT SYSDATE,
    update_date DATE DEFAULT SYSDATE,
    CONSTRAINT fk_trace_user FOREIGN KEY (user_id) REFERENCES users(id)
);

/* ==============================================
   5. AI 및 검색 테이블
   ============================================== */

CREATE SEQUENCE ai_knowledge_documents_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE ai_knowledge_documents (
    id NUMBER DEFAULT ai_knowledge_documents_seq.NEXTVAL PRIMARY KEY,
    document_type VARCHAR2(50) NOT NULL,
    source_table VARCHAR2(50) NOT NULL,
    source_id NUMBER NOT NULL,
    title VARCHAR2(200 CHAR) NOT NULL,
    content VARCHAR2(4000 CHAR) NOT NULL,
    metadata VARCHAR2(4000 CHAR),
    reg_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    update_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT chk_ai_knowledge_documents_type
        CHECK (document_type IN ('USER_LEAGUE_RECORD_SUMMARY', 'MATCH_RESULT_SUMMARY', 'LEAGUE_RECORD_SUMMARY')),
    CONSTRAINT uk_ai_knowledge_document_source
        UNIQUE (document_type, source_table, source_id)
);

CREATE SEQUENCE vectors_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE vectors (
    id NUMBER DEFAULT vectors_seq.NEXTVAL PRIMARY KEY,
    reference_id NUMBER NOT NULL,
    reference_table VARCHAR2(50) NOT NULL,
    chunk_index NUMBER DEFAULT 0 NOT NULL,
    content VARCHAR2(4000),
    metadata VARCHAR2(4000),
    embedding_vector VECTOR(1024, FLOAT32),
    reg_date DATE DEFAULT SYSDATE,
    update_date DATE DEFAULT SYSDATE,
    CONSTRAINT chk_vectors_reference_table
        CHECK (reference_table IN ('boards', 'match_infos', 'commentaries', 'speeches', 'ai_knowledge_documents'))
);

CREATE VECTOR INDEX idx_vectors_ann ON vectors(embedding_vector)
ORGANIZATION NEIGHBOR PARTITIONS
WITH TARGET ACCURACY 95 DISTANCE COSINE;

CREATE SEQUENCE speeches_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE speeches (
    id NUMBER DEFAULT speeches_seq.NEXTVAL PRIMARY KEY,
    user_id NUMBER,
    nickname VARCHAR2(255),
    chat VARCHAR2(4000),
    reg_date DATE DEFAULT SYSDATE,
    update_date DATE DEFAULT SYSDATE,
    chat_embedding_vector VECTOR(1024, FLOAT32),
    CONSTRAINT fk_speech_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE VECTOR INDEX idx_speech_ann ON speeches(chat_embedding_vector)
ORGANIZATION NEIGHBOR PARTITIONS
WITH TARGET ACCURACY 95 DISTANCE COSINE;

/* ==============================================
   6. 포인트 규칙
   ============================================== */

CREATE SEQUENCE point_rules_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE point_rules (
    id NUMBER DEFAULT point_rules_seq.NEXTVAL PRIMARY KEY,
    rule_name VARCHAR2(100) NOT NULL,
    match_type VARCHAR2(50),
    result VARCHAR2(10),
    tier_diff NUMBER,
    point NUMBER NOT NULL,
    description VARCHAR2(255),
    reg_date DATE DEFAULT SYSDATE,
    update_date DATE DEFAULT SYSDATE
);

/* ==============================================
   7. 기존 드래프트 테이블
      FIXED_ORDER 단일 구조
   ============================================== */

CREATE SEQUENCE draft_sessions_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE draft_sessions (
    id NUMBER DEFAULT draft_sessions_seq.NEXTVAL PRIMARY KEY,
    title VARCHAR2(200 CHAR) NOT NULL,
    owner_user_id NUMBER,
    proleague_id NUMBER,
    status VARCHAR2(20 CHAR) DEFAULT 'READY' NOT NULL,
    order_mode VARCHAR2(50 CHAR) DEFAULT 'BASIC' NOT NULL,
    team_count NUMBER(2) NOT NULL,
    pick_time_seconds NUMBER(4) NOT NULL,
    current_pick_no NUMBER(6) DEFAULT 1 NOT NULL,
    current_draft_team_id NUMBER,
    deadline_at TIMESTAMP,
    started_at TIMESTAMP,
    ended_at TIMESTAMP,
    reg_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    update_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_draft_sessions_owner_user
        FOREIGN KEY (owner_user_id) REFERENCES users(id),
    CONSTRAINT fk_draft_sessions_proleague
        FOREIGN KEY (proleague_id) REFERENCES leagues(id),
    CONSTRAINT chk_draft_sessions_status
        CHECK (status IN ('READY', 'LIVE', 'PAUSED', 'FINISHED', 'CANCELLED')),
    CONSTRAINT chk_draft_sessions_team_count
        CHECK (team_count > 1),
    CONSTRAINT chk_draft_sessions_pick_time
        CHECK (pick_time_seconds > 0),
    CONSTRAINT chk_draft_sessions_current_pick
        CHECK (current_pick_no > 0)
);

CREATE SEQUENCE draft_teams_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE draft_teams (
    id NUMBER DEFAULT draft_teams_seq.NEXTVAL PRIMARY KEY,
    draft_session_id NUMBER NOT NULL,
    team_name VARCHAR2(100 CHAR) NOT NULL,
    display_order NUMBER(3) NOT NULL,
    picker_user_id NUMBER,
    proleague_team_id NUMBER,
    reg_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    update_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_draft_teams_session
        FOREIGN KEY (draft_session_id) REFERENCES draft_sessions(id),
    CONSTRAINT fk_draft_teams_picker_user
        FOREIGN KEY (picker_user_id) REFERENCES users(id),
    CONSTRAINT fk_draft_teams_proleague_team
        FOREIGN KEY (proleague_team_id) REFERENCES proleague_teams(id),
    CONSTRAINT uq_draft_teams_session_name
        UNIQUE (draft_session_id, team_name),
    CONSTRAINT uq_draft_teams_session_order
        UNIQUE (draft_session_id, display_order),
    CONSTRAINT uq_draft_teams_session_proleague_team
        UNIQUE (draft_session_id, proleague_team_id),
    CONSTRAINT uq_draft_teams_id_session
        UNIQUE (id, draft_session_id),
    CONSTRAINT chk_draft_teams_display_order
        CHECK (display_order > 0)
);

CREATE TABLE draft_candidates (
    draft_session_id NUMBER NOT NULL,
    candidate_user_id NUMBER NOT NULL,
    candidate_name VARCHAR2(100 CHAR) NOT NULL,
    race VARCHAR2(20 CHAR),
    status VARCHAR2(20 CHAR) DEFAULT 'WAITING' NOT NULL,
    picked_draft_team_id NUMBER,
    picked_at TIMESTAMP,
    reg_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    update_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_draft_candidates
        PRIMARY KEY (draft_session_id, candidate_user_id),
    CONSTRAINT fk_draft_candidates_session
        FOREIGN KEY (draft_session_id) REFERENCES draft_sessions(id),
    CONSTRAINT fk_draft_candidates_user
        FOREIGN KEY (candidate_user_id) REFERENCES users(id),
    CONSTRAINT fk_draft_candidates_picked_team
        FOREIGN KEY (picked_draft_team_id, draft_session_id)
        REFERENCES draft_teams(id, draft_session_id),
    CONSTRAINT chk_draft_candidates_race
        CHECK (race IS NULL OR race IN ('ZERG', 'TERRAN', 'PROTOSS', 'RANDOM')),
    CONSTRAINT chk_draft_candidates_status
        CHECK (status IN ('WAITING', 'PICKED', 'SKIPPED', 'EXCLUDED'))
);

CREATE TABLE draft_orders (
    draft_session_id NUMBER NOT NULL,
    pick_no NUMBER(6) NOT NULL,
    draft_team_id NUMBER NOT NULL,
    reg_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    update_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_draft_orders
        PRIMARY KEY (draft_session_id, pick_no),
    CONSTRAINT fk_draft_orders_session
        FOREIGN KEY (draft_session_id) REFERENCES draft_sessions(id),
    CONSTRAINT fk_draft_orders_team
        FOREIGN KEY (draft_team_id, draft_session_id)
        REFERENCES draft_teams(id, draft_session_id),
    CONSTRAINT chk_draft_orders_pick_no
        CHECK (pick_no > 0)
);

CREATE TABLE draft_picks (
    draft_session_id NUMBER NOT NULL,
    pick_no NUMBER(6) NOT NULL,
    draft_team_id NUMBER NOT NULL,
    candidate_user_id NUMBER NOT NULL,
    picked_by_user_id NUMBER NOT NULL,
    picked_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    reg_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    update_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_draft_picks
        PRIMARY KEY (draft_session_id, pick_no),
    CONSTRAINT fk_draft_picks_session
        FOREIGN KEY (draft_session_id) REFERENCES draft_sessions(id),
    CONSTRAINT fk_draft_picks_team
        FOREIGN KEY (draft_team_id, draft_session_id)
        REFERENCES draft_teams(id, draft_session_id),
    CONSTRAINT fk_draft_picks_candidate
        FOREIGN KEY (draft_session_id, candidate_user_id)
        REFERENCES draft_candidates(draft_session_id, candidate_user_id),
    CONSTRAINT fk_draft_picks_picked_by_user
        FOREIGN KEY (picked_by_user_id) REFERENCES users(id),
    CONSTRAINT uq_draft_picks_session_candidate
        UNIQUE (draft_session_id, candidate_user_id),
    CONSTRAINT chk_draft_picks_pick_no
        CHECK (pick_no > 0)
);

ALTER TABLE draft_sessions
    ADD CONSTRAINT fk_draft_sessions_current_team
        FOREIGN KEY (current_draft_team_id, id)
        REFERENCES draft_teams(id, draft_session_id);

ALTER TABLE leagues
    ADD CONSTRAINT fk_leagues_draft_session
        FOREIGN KEY (draft_session_id) REFERENCES draft_sessions(id);

ALTER TABLE leagues
    ADD CONSTRAINT fk_leagues_champion_team
        FOREIGN KEY (champion_team_id) REFERENCES proleague_teams(id);

ALTER TABLE leagues
    ADD CONSTRAINT fk_leagues_runner_up_team
        FOREIGN KEY (runner_up_team_id) REFERENCES proleague_teams(id);

ALTER TABLE proleague_teams
    ADD CONSTRAINT fk_proleague_team_draft_team
        FOREIGN KEY (draft_team_id) REFERENCES draft_teams(id);

/* ==============================================
   8. 가위바위보 드래프트 테이블
   기존 draft_* 와 별도 운영
   2팀 전용
   ============================================== */

CREATE SEQUENCE rps_draft_sessions_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE rps_draft_sessions (
    id NUMBER DEFAULT rps_draft_sessions_seq.NEXTVAL PRIMARY KEY,
    title VARCHAR2(200 CHAR) NOT NULL,
    owner_user_id NUMBER NOT NULL,
    status VARCHAR2(20 CHAR) DEFAULT 'RPS_PENDING' NOT NULL,
    current_pick_no NUMBER(6) DEFAULT 1 NOT NULL,
    current_draft_team_id NUMBER,
    pending_draft_team_id NUMBER,
    team1_rps_choice VARCHAR2(10 CHAR),
    team2_rps_choice VARCHAR2(10 CHAR),
    rps_result VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
    started_at TIMESTAMP,
    ended_at TIMESTAMP,
    reg_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    update_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_rps_draft_sessions_owner_user
        FOREIGN KEY (owner_user_id) REFERENCES users(id),
    CONSTRAINT chk_rps_draft_sessions_status
        CHECK (status IN ('RPS_PENDING', 'PICKING', 'FINISHED')),
    CONSTRAINT chk_rps_draft_sessions_current_pick
        CHECK (current_pick_no > 0),
    CONSTRAINT chk_rps_draft_sessions_team1_choice
        CHECK (team1_rps_choice IS NULL OR team1_rps_choice IN ('ROCK', 'PAPER', 'SCISSORS')),
    CONSTRAINT chk_rps_draft_sessions_team2_choice
        CHECK (team2_rps_choice IS NULL OR team2_rps_choice IN ('ROCK', 'PAPER', 'SCISSORS')),
    CONSTRAINT chk_rps_draft_sessions_result
        CHECK (rps_result IN ('PENDING', 'DRAW', 'TEAM1_WIN', 'TEAM2_WIN'))
);

CREATE SEQUENCE rps_draft_teams_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE rps_draft_teams (
    id NUMBER DEFAULT rps_draft_teams_seq.NEXTVAL PRIMARY KEY,
    rps_draft_session_id NUMBER NOT NULL,
    team_name VARCHAR2(100 CHAR) NOT NULL,
    display_order NUMBER(1) NOT NULL,
    picker_user_id NUMBER,
    reg_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    update_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_rps_draft_teams_session
        FOREIGN KEY (rps_draft_session_id) REFERENCES rps_draft_sessions(id),
    CONSTRAINT fk_rps_draft_teams_picker_user
        FOREIGN KEY (picker_user_id) REFERENCES users(id),
    CONSTRAINT uq_rps_draft_teams_session_name
        UNIQUE (rps_draft_session_id, team_name),
    CONSTRAINT uq_rps_draft_teams_session_order
        UNIQUE (rps_draft_session_id, display_order),
    CONSTRAINT uq_rps_draft_teams_session_picker
        UNIQUE (rps_draft_session_id, picker_user_id),
    CONSTRAINT uq_rps_draft_teams_id_session
        UNIQUE (id, rps_draft_session_id),
    CONSTRAINT chk_rps_draft_teams_display_order
        CHECK (display_order IN (1, 2))
);

CREATE SEQUENCE rps_draft_candidates_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE rps_draft_candidates (
    id NUMBER DEFAULT rps_draft_candidates_seq.NEXTVAL PRIMARY KEY,
    rps_draft_session_id NUMBER NOT NULL,
    candidate_name VARCHAR2(100 CHAR) NOT NULL,
    display_order NUMBER(6) NOT NULL,
    status VARCHAR2(20 CHAR) DEFAULT 'WAITING' NOT NULL,
    picked_rps_draft_team_id NUMBER,
    picked_at TIMESTAMP,
    reg_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    update_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_rps_draft_candidates_session
        FOREIGN KEY (rps_draft_session_id) REFERENCES rps_draft_sessions(id),
    CONSTRAINT fk_rps_draft_candidates_picked_team
        FOREIGN KEY (picked_rps_draft_team_id, rps_draft_session_id)
        REFERENCES rps_draft_teams(id, rps_draft_session_id),
    CONSTRAINT uq_rps_draft_candidates_session_name
        UNIQUE (rps_draft_session_id, candidate_name),
    CONSTRAINT uq_rps_draft_candidates_session_order
        UNIQUE (rps_draft_session_id, display_order),
    CONSTRAINT uq_rps_draft_candidates_id_session
        UNIQUE (id, rps_draft_session_id),
    CONSTRAINT chk_rps_draft_candidates_order
        CHECK (display_order > 0),
    CONSTRAINT chk_rps_draft_candidates_status
        CHECK (status IN ('WAITING', 'PICKED', 'EXCLUDED'))
);

CREATE TABLE rps_draft_picks (
    rps_draft_session_id NUMBER NOT NULL,
    pick_no NUMBER(6) NOT NULL,
    rps_draft_team_id NUMBER NOT NULL,
    candidate_id NUMBER NOT NULL,
    picked_by_user_id NUMBER NOT NULL,
    picked_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    reg_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    update_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_rps_draft_picks
        PRIMARY KEY (rps_draft_session_id, pick_no),
    CONSTRAINT fk_rps_draft_picks_session
        FOREIGN KEY (rps_draft_session_id) REFERENCES rps_draft_sessions(id),
    CONSTRAINT fk_rps_draft_picks_team
        FOREIGN KEY (rps_draft_team_id, rps_draft_session_id)
        REFERENCES rps_draft_teams(id, rps_draft_session_id),
    CONSTRAINT fk_rps_draft_picks_candidate
        FOREIGN KEY (candidate_id, rps_draft_session_id)
        REFERENCES rps_draft_candidates(id, rps_draft_session_id),
    CONSTRAINT fk_rps_draft_picks_picked_by_user
        FOREIGN KEY (picked_by_user_id) REFERENCES users(id),
    CONSTRAINT uq_rps_draft_picks_session_candidate
        UNIQUE (rps_draft_session_id, candidate_id),
    CONSTRAINT chk_rps_draft_picks_pick_no
        CHECK (pick_no > 0)
);

ALTER TABLE rps_draft_sessions
    ADD CONSTRAINT fk_rps_draft_sessions_current_team
        FOREIGN KEY (current_draft_team_id, id)
        REFERENCES rps_draft_teams(id, rps_draft_session_id);

ALTER TABLE rps_draft_sessions
    ADD CONSTRAINT fk_rps_draft_sessions_pending_team
        FOREIGN KEY (pending_draft_team_id, id)
        REFERENCES rps_draft_teams(id, rps_draft_session_id);

/* ==============================================
   9. 토너먼트 대진표 테이블
   듀얼 조별전과 싱글 엘리미네이션 공통 구조
   ============================================== */

/* ==============================================
   Entry submission tables
   ============================================== */

CREATE SEQUENCE entry_submission_sessions_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE entry_submission_sessions (
    id NUMBER DEFAULT entry_submission_sessions_seq.NEXTVAL PRIMARY KEY,
    title VARCHAR2(200 CHAR) NOT NULL,
    owner_user_id NUMBER NOT NULL,
    status VARCHAR2(20 CHAR) DEFAULT 'SUBMITTING' NOT NULL,
    set_count NUMBER(6) NOT NULL,
    completed_at TIMESTAMP,
    reg_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    update_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_entry_submission_sessions_owner
        FOREIGN KEY (owner_user_id) REFERENCES users(id),
    CONSTRAINT chk_entry_submission_sessions_status
        CHECK (status IN ('SUBMITTING', 'COMPLETED')),
    CONSTRAINT chk_entry_submission_sessions_sets
        CHECK (set_count > 0)
);

CREATE SEQUENCE entry_submission_teams_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE entry_submission_teams (
    id NUMBER DEFAULT entry_submission_teams_seq.NEXTVAL PRIMARY KEY,
    entry_submission_session_id NUMBER NOT NULL,
    team_name VARCHAR2(100 CHAR) NOT NULL,
    display_order NUMBER(1) NOT NULL,
    captain_user_id NUMBER NOT NULL,
    submitted_at TIMESTAMP,
    CONSTRAINT fk_entry_submission_teams_session
        FOREIGN KEY (entry_submission_session_id) REFERENCES entry_submission_sessions(id),
    CONSTRAINT fk_entry_submission_teams_captain
        FOREIGN KEY (captain_user_id) REFERENCES users(id),
    CONSTRAINT uq_entry_submission_teams_session_order
        UNIQUE (entry_submission_session_id, display_order),
    CONSTRAINT uq_entry_submission_teams_session_captain
        UNIQUE (entry_submission_session_id, captain_user_id),
    CONSTRAINT uq_entry_submission_teams_id_session
        UNIQUE (id, entry_submission_session_id),
    CONSTRAINT chk_entry_submission_teams_order
        CHECK (display_order IN (1, 2))
);

CREATE SEQUENCE entry_submission_players_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE entry_submission_players (
    id NUMBER DEFAULT entry_submission_players_seq.NEXTVAL PRIMARY KEY,
    entry_submission_session_id NUMBER NOT NULL,
    entry_submission_team_id NUMBER NOT NULL,
    player_name VARCHAR2(100 CHAR) NOT NULL,
    display_order NUMBER(6) NOT NULL,
    captain_yn CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT fk_entry_submission_players_session
        FOREIGN KEY (entry_submission_session_id) REFERENCES entry_submission_sessions(id),
    CONSTRAINT fk_entry_submission_players_team
        FOREIGN KEY (entry_submission_team_id, entry_submission_session_id)
        REFERENCES entry_submission_teams(id, entry_submission_session_id),
    CONSTRAINT uq_entry_submission_players_team_name
        UNIQUE (entry_submission_team_id, player_name),
    CONSTRAINT uq_entry_submission_players_team_order
        UNIQUE (entry_submission_team_id, display_order),
    CONSTRAINT uq_entry_submission_players_id_session
        UNIQUE (id, entry_submission_session_id),
    CONSTRAINT chk_entry_submission_players_order
        CHECK (display_order > 0),
    CONSTRAINT chk_entry_submission_players_captain
        CHECK (captain_yn IN ('Y', 'N'))
);

CREATE TABLE entry_submission_entries (
    entry_submission_session_id NUMBER NOT NULL,
    entry_submission_team_id NUMBER NOT NULL,
    set_no NUMBER(6) NOT NULL,
    entry_submission_player_id NUMBER NOT NULL,
    submitted_by_user_id NUMBER NOT NULL,
    submitted_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_entry_submission_entries
        PRIMARY KEY (entry_submission_session_id, entry_submission_team_id, set_no),
    CONSTRAINT fk_entry_submission_entries_session
        FOREIGN KEY (entry_submission_session_id) REFERENCES entry_submission_sessions(id),
    CONSTRAINT fk_entry_submission_entries_team
        FOREIGN KEY (entry_submission_team_id, entry_submission_session_id)
        REFERENCES entry_submission_teams(id, entry_submission_session_id),
    CONSTRAINT fk_entry_submission_entries_player
        FOREIGN KEY (entry_submission_player_id, entry_submission_session_id)
        REFERENCES entry_submission_players(id, entry_submission_session_id),
    CONSTRAINT fk_entry_submission_entries_submitter
        FOREIGN KEY (submitted_by_user_id) REFERENCES users(id),
    CONSTRAINT chk_entry_submission_entries_set_no
        CHECK (set_no > 0)
);

CREATE SEQUENCE tournaments_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE tournaments (
    id NUMBER DEFAULT tournaments_seq.NEXTVAL PRIMARY KEY,
    title VARCHAR2(200 CHAR) NOT NULL,
    owner_user_id NUMBER,
    status VARCHAR2(20 CHAR) DEFAULT 'LIVE' NOT NULL,
    reg_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    update_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_tournaments_owner_user
        FOREIGN KEY (owner_user_id) REFERENCES users(id),
    CONSTRAINT chk_tournaments_status
        CHECK (status IN ('LIVE', 'FINISHED'))
);

ALTER TABLE leagues
    ADD CONSTRAINT fk_leagues_tournament
        FOREIGN KEY (tournament_id) REFERENCES tournaments(id);

CREATE SEQUENCE tournament_participants_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE tournament_participants (
    id NUMBER DEFAULT tournament_participants_seq.NEXTVAL PRIMARY KEY,
    tournament_id NUMBER NOT NULL,
    user_id NUMBER,
    participant_name VARCHAR2(100 CHAR),
    seed_no NUMBER(6),
    status VARCHAR2(20 CHAR) DEFAULT 'READY' NOT NULL,
    reg_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    update_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_tournament_participants_tournament
        FOREIGN KEY (tournament_id) REFERENCES tournaments(id),
    CONSTRAINT fk_tournament_participants_user
        FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uq_tournament_participants_seed
        UNIQUE (tournament_id, seed_no),
    CONSTRAINT chk_tournament_participants_status
        CHECK (status IN ('READY', 'WAITING', 'DROPPED')),
    CONSTRAINT chk_tournament_participants_name
        CHECK (user_id IS NOT NULL OR participant_name IS NOT NULL)
);

CREATE SEQUENCE tournament_stages_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE tournament_stages (
    id NUMBER DEFAULT tournament_stages_seq.NEXTVAL PRIMARY KEY,
    tournament_id NUMBER NOT NULL,
    stage_no NUMBER(3) NOT NULL,
    stage_name VARCHAR2(100 CHAR) NOT NULL,
    stage_type VARCHAR2(30 CHAR) NOT NULL,
    status VARCHAR2(20 CHAR) DEFAULT 'DRAFT' NOT NULL,
    display_order NUMBER(3) NOT NULL,
    reg_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    update_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_tournament_stages_tournament
        FOREIGN KEY (tournament_id) REFERENCES tournaments(id),
    CONSTRAINT uq_tournament_stages_no
        UNIQUE (tournament_id, stage_no),
    CONSTRAINT chk_tournament_stages_type
        CHECK (stage_type IN ('DUAL_GROUP', 'SINGLE_ELIMINATION', 'ULTIMATE_BATTLE', 'RACE_SURVIVAL')),
    CONSTRAINT chk_tournament_stages_status
        CHECK (status IN ('DRAFT', 'READY', 'FINISHED'))
);

CREATE SEQUENCE tournament_groups_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE tournament_groups (
    id NUMBER DEFAULT tournament_groups_seq.NEXTVAL PRIMARY KEY,
    stage_id NUMBER NOT NULL,
    group_code VARCHAR2(20 CHAR) NOT NULL,
    group_name VARCHAR2(100 CHAR) NOT NULL,
    display_order NUMBER(3) NOT NULL,
    reg_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    update_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_tournament_groups_stage
        FOREIGN KEY (stage_id) REFERENCES tournament_stages(id),
    CONSTRAINT uq_tournament_groups_code
        UNIQUE (stage_id, group_code)
);

CREATE SEQUENCE tournament_group_entries_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE tournament_group_entries (
    id NUMBER DEFAULT tournament_group_entries_seq.NEXTVAL PRIMARY KEY,
    group_id NUMBER NOT NULL,
    participant_id NUMBER NOT NULL,
    group_seed_no NUMBER(6) NOT NULL,
    entry_label VARCHAR2(30 CHAR),
    reg_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    update_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_tournament_group_entries_group
        FOREIGN KEY (group_id) REFERENCES tournament_groups(id),
    CONSTRAINT fk_tournament_group_entries_participant
        FOREIGN KEY (participant_id) REFERENCES tournament_participants(id),
    CONSTRAINT uq_tournament_group_entries_seed
        UNIQUE (group_id, group_seed_no),
    CONSTRAINT uq_tournament_group_entries_participant
        UNIQUE (group_id, participant_id)
);

CREATE SEQUENCE tournament_matches_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE tournament_matches (
    id NUMBER DEFAULT tournament_matches_seq.NEXTVAL PRIMARY KEY,
    stage_id NUMBER NOT NULL,
    group_id NUMBER NOT NULL,
    match_key VARCHAR2(50 CHAR) NOT NULL,
    match_role VARCHAR2(30 CHAR) NOT NULL,
    round_no NUMBER(3),
    match_no NUMBER(6),
    display_name VARCHAR2(100 CHAR) NOT NULL,
    best_of NUMBER DEFAULT 3 NOT NULL,
    status VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
    winner_participant_id NUMBER,
    map_id NUMBER,
    scheduled_at TIMESTAMP,
    layout_col NUMBER(3),
    layout_row NUMBER(3),
    display_order NUMBER(6) NOT NULL,
    reg_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    update_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_tournament_matches_stage
        FOREIGN KEY (stage_id) REFERENCES tournament_stages(id),
    CONSTRAINT fk_tournament_matches_group
        FOREIGN KEY (group_id) REFERENCES tournament_groups(id),
    CONSTRAINT fk_tournament_matches_winner
        FOREIGN KEY (winner_participant_id) REFERENCES tournament_participants(id),
    CONSTRAINT fk_tournament_matches_map
        FOREIGN KEY (map_id) REFERENCES maps(id),
    CONSTRAINT uq_tournament_matches_key
        UNIQUE (group_id, match_key),
    CONSTRAINT chk_tournament_matches_role
        CHECK (match_role IN ('OPENING', 'WINNERS', 'LOSERS', 'DECIDER', 'ROUND', 'FINAL')),
    CONSTRAINT chk_tournament_matches_status
        CHECK (status IN ('PENDING', 'READY', 'FINISHED', 'CANCELLED')),
    CONSTRAINT chk_tournament_matches_best_of
        CHECK (best_of > 0 AND MOD(best_of, 2) = 1)
);

CREATE SEQUENCE tournament_match_slots_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE tournament_match_slots (
    id NUMBER DEFAULT tournament_match_slots_seq.NEXTVAL PRIMARY KEY,
    match_id NUMBER NOT NULL,
    slot_no NUMBER(1) NOT NULL,
    participant_id NUMBER,
    source_match_id NUMBER,
    source_outcome VARCHAR2(10 CHAR),
    placeholder_label VARCHAR2(100 CHAR),
    score NUMBER(3),
    is_winner NUMBER(1) DEFAULT 0 NOT NULL,
    is_bye NUMBER(1) DEFAULT 0 NOT NULL,
    reg_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    update_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_tournament_match_slots_match
        FOREIGN KEY (match_id) REFERENCES tournament_matches(id),
    CONSTRAINT fk_tournament_match_slots_participant
        FOREIGN KEY (participant_id) REFERENCES tournament_participants(id),
    CONSTRAINT fk_tournament_match_slots_source_match
        FOREIGN KEY (source_match_id) REFERENCES tournament_matches(id),
    CONSTRAINT uq_tournament_match_slots_no
        UNIQUE (match_id, slot_no),
    CONSTRAINT chk_tournament_match_slots_slot_no
        CHECK (slot_no IN (1, 2)),
    CONSTRAINT chk_tournament_match_slots_source
        CHECK (source_outcome IS NULL OR source_outcome IN ('WINNER', 'LOSER')),
    CONSTRAINT chk_tournament_match_slots_score
        CHECK (score IS NULL OR score >= 0),
    CONSTRAINT chk_tournament_match_slots_winner
        CHECK (is_winner IN (0, 1)),
    CONSTRAINT chk_tournament_match_slots_bye
        CHECK (is_bye IN (0, 1))
);

CREATE SEQUENCE tournament_match_score_submissions_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE tournament_match_score_submissions (
    id NUMBER DEFAULT tournament_match_score_submissions_seq.NEXTVAL PRIMARY KEY,
    tournament_id NUMBER NOT NULL,
    match_id NUMBER NOT NULL,
    submitted_by_user_id NUMBER NOT NULL,
    submitted_by_participant_id NUMBER,
    submitter_role VARCHAR2(20 CHAR) NOT NULL,
    slot1_score NUMBER(3) NOT NULL,
    slot2_score NUMBER(3) NOT NULL,
    winner_slot_no NUMBER(1) NOT NULL,
    status VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
    admin_reviewer_user_id NUMBER,
    admin_reviewed_at TIMESTAMP,
    admin_note VARCHAR2(1000 CHAR),
    reg_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    update_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_tournament_score_sub_tournament
        FOREIGN KEY (tournament_id) REFERENCES tournaments(id),
    CONSTRAINT fk_tournament_score_sub_match
        FOREIGN KEY (match_id) REFERENCES tournament_matches(id),
    CONSTRAINT fk_tournament_score_sub_user
        FOREIGN KEY (submitted_by_user_id) REFERENCES users(id),
    CONSTRAINT fk_tournament_score_sub_participant
        FOREIGN KEY (submitted_by_participant_id) REFERENCES tournament_participants(id),
    CONSTRAINT fk_tournament_score_sub_reviewer
        FOREIGN KEY (admin_reviewer_user_id) REFERENCES users(id),
    CONSTRAINT chk_tournament_score_sub_role
        CHECK (submitter_role IN ('PLAYER', 'ADMIN')),
    CONSTRAINT chk_tournament_score_sub_status
        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT chk_tournament_score_sub_slot1
        CHECK (slot1_score >= 0),
    CONSTRAINT chk_tournament_score_sub_slot2
        CHECK (slot2_score >= 0),
    CONSTRAINT chk_tournament_score_sub_winner
        CHECK (winner_slot_no IN (1, 2))
);

CREATE SEQUENCE race_survival_progress_submissions_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE race_survival_progress_submissions (
    id NUMBER DEFAULT race_survival_progress_submissions_seq.NEXTVAL PRIMARY KEY,
    tournament_id NUMBER NOT NULL,
    submitted_by_user_id NUMBER NOT NULL,
    status VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
    reviewed_by_user_id NUMBER,
    admin_note VARCHAR2(1000 CHAR),
    reg_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    reviewed_at TIMESTAMP,
    update_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_race_survival_progress_tournament
        FOREIGN KEY (tournament_id) REFERENCES tournaments(id),
    CONSTRAINT fk_race_survival_progress_submitter
        FOREIGN KEY (submitted_by_user_id) REFERENCES users(id),
    CONSTRAINT fk_race_survival_progress_reviewer
        FOREIGN KEY (reviewed_by_user_id) REFERENCES users(id),
    CONSTRAINT chk_race_survival_progress_status
        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

CREATE SEQUENCE race_survival_progress_sub_matches_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE race_survival_progress_submission_matches (
    id NUMBER DEFAULT race_survival_progress_sub_matches_seq.NEXTVAL PRIMARY KEY,
    submission_id NUMBER NOT NULL,
    match_order NUMBER(6) NOT NULL,
    map_id NUMBER,
    slot1_participant_id NUMBER NOT NULL,
    slot2_participant_id NUMBER NOT NULL,
    slot1_score NUMBER(1) NOT NULL,
    slot2_score NUMBER(1) NOT NULL,
    reg_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    update_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_race_survival_progress_match_sub
        FOREIGN KEY (submission_id) REFERENCES race_survival_progress_submissions(id),
    CONSTRAINT fk_race_survival_progress_match_map
        FOREIGN KEY (map_id) REFERENCES maps(id),
    CONSTRAINT fk_race_survival_progress_match_slot1
        FOREIGN KEY (slot1_participant_id) REFERENCES tournament_participants(id),
    CONSTRAINT fk_race_survival_progress_match_slot2
        FOREIGN KEY (slot2_participant_id) REFERENCES tournament_participants(id),
    CONSTRAINT uq_race_survival_progress_match_order
        UNIQUE (submission_id, match_order),
    CONSTRAINT chk_race_survival_progress_match_order
        CHECK (match_order > 0),
    CONSTRAINT chk_race_survival_progress_match_scores
        CHECK (
            (slot1_score = 1 AND slot2_score = 0)
            OR (slot1_score = 0 AND slot2_score = 1)
        ),
    CONSTRAINT chk_race_survival_progress_match_slots
        CHECK (slot1_participant_id <> slot2_participant_id)
);

CREATE SEQUENCE tournament_result_slots_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE tournament_result_slots (
    id NUMBER DEFAULT tournament_result_slots_seq.NEXTVAL PRIMARY KEY,
    stage_id NUMBER NOT NULL,
    group_id NUMBER,
    result_key VARCHAR2(50 CHAR) NOT NULL,
    result_type VARCHAR2(30 CHAR) NOT NULL,
    rank_no NUMBER(3),
    label VARCHAR2(100 CHAR) NOT NULL,
    participant_id NUMBER,
    decided_at TIMESTAMP,
    reg_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    update_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_tournament_result_slots_stage
        FOREIGN KEY (stage_id) REFERENCES tournament_stages(id),
    CONSTRAINT fk_tournament_result_slots_group
        FOREIGN KEY (group_id) REFERENCES tournament_groups(id),
    CONSTRAINT fk_tournament_result_slots_participant
        FOREIGN KEY (participant_id) REFERENCES tournament_participants(id),
    CONSTRAINT uq_tournament_result_slots_key
        UNIQUE (stage_id, result_key),
    CONSTRAINT chk_tournament_result_slots_type
        CHECK (result_type IN ('QUALIFIED', 'CHAMPION', 'RUNNER_UP', 'ELIMINATED'))
);

CREATE SEQUENCE tournament_routes_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE tournament_routes (
    id NUMBER DEFAULT tournament_routes_seq.NEXTVAL PRIMARY KEY,
    from_match_id NUMBER NOT NULL,
    outcome VARCHAR2(10 CHAR) NOT NULL,
    target_type VARCHAR2(20 CHAR) NOT NULL,
    to_match_id NUMBER,
    to_slot_no NUMBER(1),
    to_result_slot_id NUMBER,
    reg_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    update_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_tournament_routes_from_match
        FOREIGN KEY (from_match_id) REFERENCES tournament_matches(id),
    CONSTRAINT fk_tournament_routes_to_match
        FOREIGN KEY (to_match_id) REFERENCES tournament_matches(id),
    CONSTRAINT fk_tournament_routes_result_slot
        FOREIGN KEY (to_result_slot_id) REFERENCES tournament_result_slots(id),
    CONSTRAINT uq_tournament_routes_outcome
        UNIQUE (from_match_id, outcome),
    CONSTRAINT chk_tournament_routes_outcome
        CHECK (outcome IN ('WINNER', 'LOSER')),
    CONSTRAINT chk_tournament_routes_target
        CHECK (target_type IN ('MATCH_SLOT', 'RESULT_SLOT', 'ELIMINATED')),
    CONSTRAINT chk_tournament_routes_to_slot
        CHECK (to_slot_no IS NULL OR to_slot_no IN (1, 2)),
    CONSTRAINT chk_tournament_routes_target_cols
        CHECK (
            (target_type = 'MATCH_SLOT' AND to_match_id IS NOT NULL AND to_slot_no IS NOT NULL AND to_result_slot_id IS NULL)
            OR (target_type = 'RESULT_SLOT' AND to_match_id IS NULL AND to_slot_no IS NULL AND to_result_slot_id IS NOT NULL)
            OR (target_type = 'ELIMINATED' AND to_match_id IS NULL AND to_slot_no IS NULL AND to_result_slot_id IS NULL)
        )
);

/* ==============================================
   10. 공식 전적 뷰 및 인덱스
   ============================================== */

CREATE OR REPLACE VIEW v_user_match_results AS
SELECT
    l.id AS league_id,
    l.league_name AS league_name,
    l.league_type AS league_type,
    t.id AS tournament_id,
    m.id AS match_id,
    s.id AS slot_id,
    p.user_id AS user_id,
    u.user_id AS login_id,
    p.id AS participant_id,
    op.user_id AS opponent_user_id,
    ou.user_id AS opponent_login_id,
    CASE WHEN s.is_winner = 1 THEN 'WIN' ELSE 'LOSE' END AS result,
    s.score AS score_for,
    os.score AS score_against,
    s.is_bye AS is_bye,
    m.update_date AS decided_at,
    'TOURNAMENT' AS source_type
FROM leagues l
JOIN tournaments t
    ON t.id = l.tournament_id
JOIN tournament_participants p
    ON p.tournament_id = t.id
JOIN users u
    ON u.id = p.user_id
JOIN tournament_match_slots s
    ON s.participant_id = p.id
   AND s.is_bye = 0
JOIN tournament_matches m
    ON m.id = s.match_id
   AND m.status = 'FINISHED'
   AND m.winner_participant_id IS NOT NULL
JOIN tournament_match_slots os
    ON os.match_id = s.match_id
   AND os.id <> s.id
   AND os.participant_id IS NOT NULL
   AND os.is_bye = 0
JOIN tournament_participants op
    ON op.id = os.participant_id
LEFT JOIN users ou
    ON ou.id = op.user_id
WHERE l.league_type IN ('PERSONAL', 'RACE_SURVIVAL', 'ULTIMATE_BATTLE')
UNION ALL
SELECT
    l.id AS league_id,
    l.league_name AS league_name,
    l.league_type AS league_type,
    CAST(NULL AS NUMBER) AS tournament_id,
    mi.id AS match_id,
    mp.id AS slot_id,
    mp.user_id AS user_id,
    u.user_id AS login_id,
    CAST(NULL AS NUMBER) AS participant_id,
    CAST(NULL AS NUMBER) AS opponent_user_id,
    CAST(NULL AS VARCHAR2(255 CHAR)) AS opponent_login_id,
    mp.result AS result,
    CAST(NULL AS NUMBER) AS score_for,
    CAST(NULL AS NUMBER) AS score_against,
    0 AS is_bye,
    CAST(mi.update_date AS TIMESTAMP) AS decided_at,
    'LEGACY_PROLEAGUE' AS source_type
FROM leagues l
JOIN match_infos mi
    ON mi.league_id = l.id
JOIN match_players mp
    ON mp.match_info_id = mi.id
JOIN users u
    ON u.id = mp.user_id
WHERE l.league_type = 'PROLEAGUE'
  AND mp.result IN ('WIN', 'LOSE', 'DRAW');

CREATE OR REPLACE VIEW v_user_league_records AS
SELECT
    league_id,
    league_name,
    league_type,
    user_id,
    login_id,
    COUNT(CASE WHEN result = 'WIN' THEN 1 END) AS wins,
    COUNT(CASE WHEN result = 'LOSE' THEN 1 END) AS losses,
    COUNT(CASE WHEN result = 'DRAW' THEN 1 END) AS draws,
    SUM(NVL(score_for, 0)) AS score_for,
    SUM(NVL(score_against, 0)) AS score_against,
    MIN(source_type) AS source_type
FROM v_user_match_results
GROUP BY
    league_id,
    league_name,
    league_type,
    user_id,
    login_id;

CREATE INDEX idx_proleague_teams_league ON proleague_teams(league_id);
CREATE INDEX idx_proleague_teams_leader ON proleague_teams(team_leader_id);
CREATE INDEX idx_proleague_teams_vice ON proleague_teams(vice_leader_id);
CREATE INDEX idx_proleague_teams_draft_team ON proleague_teams(draft_team_id);
CREATE INDEX idx_proleague_teams_league_order ON proleague_teams(league_id, display_order);

CREATE INDEX idx_league_part_league ON league_participations(league_id);
CREATE INDEX idx_league_part_user ON league_participations(user_id);

CREATE INDEX idx_series_infos_league ON series_infos(league_id);

CREATE INDEX idx_match_infos_league ON match_infos(league_id);
CREATE INDEX idx_match_infos_series ON match_infos(series_info_id);
CREATE INDEX idx_match_infos_map ON match_infos(map_id);

CREATE INDEX idx_match_players_user ON match_players(user_id);
CREATE INDEX idx_match_players_match ON match_players(match_info_id);
CREATE INDEX idx_match_players_team ON match_players(proleague_team_id);

CREATE INDEX idx_commentaries_match ON commentaries(match_info_id);
CREATE INDEX idx_commentaries_user ON commentaries(user_id);

CREATE INDEX idx_boards_user ON boards(user_id);
CREATE INDEX idx_boards_author_name ON boards(author_name);
CREATE INDEX idx_boards_reg_date ON boards(reg_date);

CREATE INDEX idx_comments_board ON comments(board_id);
CREATE INDEX idx_comments_user ON comments(user_id);
CREATE INDEX idx_comments_parent ON comments(parent_id);
CREATE INDEX idx_comments_author_name ON comments(author_name);
CREATE INDEX idx_comments_board_reg_date ON comments(board_id, reg_date);

CREATE INDEX idx_traces_user ON traces(user_id);

CREATE INDEX idx_ai_knowledge_documents_type ON ai_knowledge_documents(document_type);
CREATE INDEX idx_vectors_ref ON vectors(reference_table, reference_id);
CREATE UNIQUE INDEX uk_vectors_ref_chunk ON vectors(reference_table, reference_id, chunk_index);

CREATE INDEX idx_speeches_user ON speeches(user_id);

CREATE UNIQUE INDEX idx_users_active_userid ON users (
    CASE WHEN status != 'INACTIVE' THEN user_id END
);

CREATE INDEX idx_site_menu_visibility_updated_by ON site_menu_visibility(updated_by);
CREATE INDEX idx_ai_chat_settings_updated_by ON ai_chat_settings(updated_by);

CREATE INDEX idx_home_schedules_main ON home_schedules(scheduled_at, schedule_group, display_priority);
CREATE INDEX idx_home_schedules_group ON home_schedules(schedule_group, display_priority);
CREATE INDEX idx_home_schedule_matches_schedule_order ON home_schedule_matches(schedule_id, display_order, id);
CREATE INDEX idx_home_schedule_matches_map ON home_schedule_matches(map_id);
CREATE INDEX idx_home_schedule_match_players_match ON home_schedule_match_players(match_id, side, slot_order, id);
CREATE INDEX idx_home_schedule_match_players_user ON home_schedule_match_players(user_id);

CREATE INDEX idx_leagues_status ON leagues(status, update_date);
CREATE INDEX idx_leagues_type ON leagues(league_type);
CREATE INDEX idx_leagues_draft_session ON leagues(draft_session_id);
CREATE INDEX idx_leagues_tournament ON leagues(tournament_id);

CREATE INDEX idx_proleague_team_members_league ON proleague_team_members(league_id, status);
CREATE INDEX idx_proleague_team_members_team ON proleague_team_members(proleague_team_id);
CREATE INDEX idx_proleague_team_members_user ON proleague_team_members(user_id);
CREATE INDEX idx_proleague_team_members_source_draft ON proleague_team_members(source_draft_session_id);

CREATE INDEX idx_draft_sessions_status ON draft_sessions(status);
CREATE INDEX idx_draft_sessions_owner_user ON draft_sessions(owner_user_id);
CREATE INDEX idx_draft_sessions_proleague ON draft_sessions(proleague_id);
CREATE INDEX idx_draft_sessions_current_team ON draft_sessions(current_draft_team_id);

CREATE INDEX idx_draft_teams_session_id ON draft_teams(draft_session_id);
CREATE INDEX idx_draft_teams_picker_user_id ON draft_teams(picker_user_id);
CREATE INDEX idx_draft_teams_proleague_team ON draft_teams(proleague_team_id);

CREATE INDEX idx_draft_candidates_session_id ON draft_candidates(draft_session_id);
CREATE INDEX idx_draft_candidates_user_id ON draft_candidates(candidate_user_id);
CREATE INDEX idx_draft_candidates_status ON draft_candidates(draft_session_id, status);

CREATE INDEX idx_draft_orders_session_id ON draft_orders(draft_session_id);
CREATE INDEX idx_draft_orders_team_id ON draft_orders(draft_team_id);

CREATE INDEX idx_draft_picks_session_id ON draft_picks(draft_session_id);
CREATE INDEX idx_draft_picks_team_id ON draft_picks(draft_team_id);
CREATE INDEX idx_draft_picks_candidate_id ON draft_picks(candidate_user_id);

CREATE INDEX idx_rps_draft_sessions_status ON rps_draft_sessions(status);
CREATE INDEX idx_rps_draft_sessions_owner_user ON rps_draft_sessions(owner_user_id);
CREATE INDEX idx_rps_draft_sessions_current_team ON rps_draft_sessions(current_draft_team_id);
CREATE INDEX idx_rps_draft_sessions_pending_team ON rps_draft_sessions(pending_draft_team_id);

CREATE INDEX idx_rps_draft_teams_session_id ON rps_draft_teams(rps_draft_session_id);
CREATE INDEX idx_rps_draft_teams_picker_user_id ON rps_draft_teams(picker_user_id);

CREATE INDEX idx_rps_draft_candidates_session_id ON rps_draft_candidates(rps_draft_session_id);
CREATE INDEX idx_rps_draft_candidates_status ON rps_draft_candidates(rps_draft_session_id, status);
CREATE INDEX idx_rps_draft_candidates_order ON rps_draft_candidates(rps_draft_session_id, display_order);

CREATE INDEX idx_rps_draft_picks_session_id ON rps_draft_picks(rps_draft_session_id);
CREATE INDEX idx_rps_draft_picks_team_id ON rps_draft_picks(rps_draft_team_id);
CREATE INDEX idx_rps_draft_picks_candidate_id ON rps_draft_picks(candidate_id);

CREATE INDEX idx_entry_submission_sessions_status ON entry_submission_sessions(status);
CREATE INDEX idx_entry_submission_sessions_owner ON entry_submission_sessions(owner_user_id);

CREATE INDEX idx_entry_submission_teams_session ON entry_submission_teams(entry_submission_session_id);
CREATE INDEX idx_entry_submission_teams_captain ON entry_submission_teams(captain_user_id);

CREATE INDEX idx_entry_submission_players_session ON entry_submission_players(entry_submission_session_id);
CREATE INDEX idx_entry_submission_players_team ON entry_submission_players(entry_submission_team_id);

CREATE INDEX idx_entry_submission_entries_session ON entry_submission_entries(entry_submission_session_id);
CREATE INDEX idx_entry_submission_entries_team ON entry_submission_entries(entry_submission_team_id);
CREATE INDEX idx_entry_submission_entries_player ON entry_submission_entries(entry_submission_player_id);

CREATE INDEX idx_tournaments_status ON tournaments(status);
CREATE INDEX idx_tournaments_owner_user ON tournaments(owner_user_id);

CREATE INDEX idx_tournament_participants_tournament ON tournament_participants(tournament_id);
CREATE INDEX idx_tournament_participants_user ON tournament_participants(user_id);
CREATE INDEX idx_tournament_participants_status ON tournament_participants(tournament_id, status);

CREATE INDEX idx_tournament_stages_tournament ON tournament_stages(tournament_id);
CREATE INDEX idx_tournament_stages_status ON tournament_stages(tournament_id, status);

CREATE INDEX idx_tournament_groups_stage ON tournament_groups(stage_id);

CREATE INDEX idx_tournament_group_entries_group ON tournament_group_entries(group_id);
CREATE INDEX idx_tournament_group_entries_participant ON tournament_group_entries(participant_id);

CREATE INDEX idx_tournament_matches_stage ON tournament_matches(stage_id);
CREATE INDEX idx_tournament_matches_group ON tournament_matches(group_id);
CREATE INDEX idx_tournament_matches_status ON tournament_matches(stage_id, status);
CREATE INDEX idx_tournament_matches_winner ON tournament_matches(winner_participant_id);
CREATE INDEX idx_tournament_matches_map ON tournament_matches(map_id);

CREATE INDEX idx_tournament_match_slots_match ON tournament_match_slots(match_id);
CREATE INDEX idx_tournament_match_slots_participant ON tournament_match_slots(participant_id);
CREATE INDEX idx_tournament_match_slots_source ON tournament_match_slots(source_match_id);

CREATE INDEX idx_tournament_score_sub_match ON tournament_match_score_submissions(match_id);
CREATE INDEX idx_tournament_score_sub_tournament ON tournament_match_score_submissions(tournament_id);
CREATE INDEX idx_tournament_score_sub_status ON tournament_match_score_submissions(status);
CREATE INDEX idx_tournament_score_sub_user ON tournament_match_score_submissions(submitted_by_user_id);

CREATE INDEX idx_race_survival_progress_tournament ON race_survival_progress_submissions(tournament_id, status);
CREATE INDEX idx_race_survival_progress_submitter ON race_survival_progress_submissions(submitted_by_user_id);
CREATE INDEX idx_race_survival_progress_reviewed ON race_survival_progress_submissions(reviewed_by_user_id);
CREATE INDEX idx_race_survival_progress_match_sub ON race_survival_progress_submission_matches(submission_id);
CREATE INDEX idx_race_survival_progress_match_map ON race_survival_progress_submission_matches(map_id);
CREATE INDEX idx_race_survival_progress_match_slot1 ON race_survival_progress_submission_matches(slot1_participant_id);
CREATE INDEX idx_race_survival_progress_match_slot2 ON race_survival_progress_submission_matches(slot2_participant_id);

CREATE INDEX idx_tournament_result_slots_stage ON tournament_result_slots(stage_id);
CREATE INDEX idx_tournament_result_slots_group ON tournament_result_slots(group_id);
CREATE INDEX idx_tournament_result_slots_participant ON tournament_result_slots(participant_id);

CREATE INDEX idx_tournament_routes_from_match ON tournament_routes(from_match_id);
CREATE INDEX idx_tournament_routes_to_match ON tournament_routes(to_match_id);
CREATE INDEX idx_tournament_routes_result_slot ON tournament_routes(to_result_slot_id);
